/-
Copyright (c) 2026 Timaeus. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Grammar.SpatialEnergyCorrection
import Grammar.LaplaceContinuity

/-!
# Joint weak convergence of energy and location under a spatial phase (unit 371; Astra #45 unit 5)

Let `Q_N^ξ` be the chart posterior with continuous phase `ξ` and nonnegative amplitude `η`.  The
joint law of `(NK, u)` under `Q_N^ξ` (`phaseJointLaw`) converges weakly, along any `N_m → ∞`, to
the pushforward `Q̃^ξ` of the limiting joint law `Q^ξ ∝ η(P_Ju) w(u) y^{λ-1} e^{-βy+βξ(P_Ju)√y}`
under `(y,u) ↦ (y, P_J u)` (`spatialJointFaceLaw`, `spatialJointLaw_tendsto`).  The proof uses
the tightness/separating-algebra criterion on the Polish space `ℝ × ℝ^d`: the star algebra
generated by `(y,u) ↦ e^{-(s y⁺ + t y⁻)} F(u)`, `F` bounded continuous, separates points
(`jointAlgebra_separatesPoints`); on the generators the integrals are the weighted energy Laplace
transforms of Headline LXXII, which converge (`spatialLaplace_tendsto`); tightness comes from the
energy marginal (Laplace tightness) and the compact location.

**The conditional energy law is `ρ_{ξ(v)}`**: for bounded measurable `f`,
`∫ f dQ̃^ξ = ∫ η(P_Ju) w(u) J_λ(ξ(P_Ju)) (∫ f(y, P_Ju) ρ_{ξ(P_Ju)}(dy)) du / Z_ξ`
(`spatialJointFaceLaw_integral_disintegration`): energy and location are dependent in general,
independent exactly when the phase is constant on the face.
-/

open MeasureTheory Set Real Filter Topology

namespace Grammar

open BoundedContinuousFunction

variable {d : ℕ}

/-! ### The generating algebra on `ℝ × ℝ^d` -/

/-- The generating set `{(y,u) ↦ e^{-(s y⁺ + t y⁻)} F(u) : s, t ≥ 0, F bounded continuous}`. -/
def jointGenSet (d : ℕ) : Set ((ℝ × (Fin d → ℝ)) →ᵇ ℝ) :=
  {f | ∃ (s t : ℝ) (F : (Fin d → ℝ) →ᵇ ℝ), 0 ≤ s ∧ 0 ≤ t ∧
    ∀ z, f z = expSplitFun s t z.1 * F z.2}

/-- A generator as a bounded continuous function. -/
noncomputable def jointGen (s t : ℝ) (hs : 0 ≤ s) (ht : 0 ≤ t) (F : (Fin d → ℝ) →ᵇ ℝ) :
    (ℝ × (Fin d → ℝ)) →ᵇ ℝ :=
  BoundedContinuousFunction.ofNormedAddCommGroup (fun z => expSplitFun s t z.1 * F z.2)
    (((continuous_expSplitFun s t).comp continuous_fst).mul (F.continuous.comp continuous_snd))
    ‖F‖ fun z => by
      rw [norm_mul]
      calc ‖expSplitFun s t z.1‖ * ‖F z.2‖ ≤ 1 * ‖F z.2‖ :=
            mul_le_mul_of_nonneg_right (norm_expSplitFun_le_one hs ht _) (norm_nonneg _)
        _ ≤ ‖F‖ := by rw [one_mul]; exact F.norm_coe_le_norm _

theorem jointGen_apply (s t : ℝ) (hs : 0 ≤ s) (ht : 0 ≤ t) (F : (Fin d → ℝ) →ᵇ ℝ)
    (z : ℝ × (Fin d → ℝ)) : jointGen s t hs ht F z = expSplitFun s t z.1 * F z.2 := rfl

theorem jointGen_mem (s t : ℝ) (hs : 0 ≤ s) (ht : 0 ≤ t) (F : (Fin d → ℝ) →ᵇ ℝ) :
    jointGen s t hs ht F ∈ jointGenSet d :=
  ⟨s, t, F, hs, ht, fun _ => rfl⟩

theorem one_mem_jointGenSet : (1 : (ℝ × (Fin d → ℝ)) →ᵇ ℝ) ∈ jointGenSet d :=
  ⟨0, 0, 1, le_rfl, le_rfl, fun z => by simp [expSplitFun]⟩

theorem mul_mem_jointGenSet {f g : (ℝ × (Fin d → ℝ)) →ᵇ ℝ} (hf : f ∈ jointGenSet d)
    (hg : g ∈ jointGenSet d) : f * g ∈ jointGenSet d := by
  obtain ⟨s₁, t₁, F₁, hs₁, ht₁, hf⟩ := hf
  obtain ⟨s₂, t₂, F₂, hs₂, ht₂, hg⟩ := hg
  refine ⟨s₁ + s₂, t₁ + t₂, F₁ * F₂, by positivity, by positivity, fun z => ?_⟩
  rw [BoundedContinuousFunction.mul_apply, hf, hg, BoundedContinuousFunction.mul_apply]
  unfold expSplitFun
  rw [show -((s₁ + s₂) * max z.1 0 + (t₁ + t₂) * max (-z.1) 0) =
    -(s₁ * max z.1 0 + t₁ * max (-z.1) 0) + -(s₂ * max z.1 0 + t₂ * max (-z.1) 0) by ring,
    Real.exp_add]
  ring

/-- The star subalgebra generated by the energy Laplace kernels times bounded continuous functions
of the location. -/
noncomputable def jointAlgebra (d : ℕ) : StarSubalgebra ℝ ((ℝ × (Fin d → ℝ)) →ᵇ ℝ) where
  toSubalgebra := (Submodule.span ℝ (jointGenSet d)).toSubalgebra
    (Submodule.subset_span one_mem_jointGenSet) fun x y hx hy => by
      have : x * y ∈ Submodule.span ℝ (jointGenSet d) * Submodule.span ℝ (jointGenSet d) :=
        Submodule.mul_mem_mul hx hy
      rw [Submodule.span_mul_span] at this
      exact Submodule.span_mono
        (Set.mul_subset_iff.2 fun f hf g hg => mul_mem_jointGenSet hf hg) this
  star_mem' := fun {f} hf => by
    rwa [show star f = f from BoundedContinuousFunction.ext fun z => by simp]

theorem mem_jointAlgebra {f : (ℝ × (Fin d → ℝ)) →ᵇ ℝ} :
    f ∈ jointAlgebra d ↔ f ∈ Submodule.span ℝ (jointGenSet d) := Iff.rfl

theorem jointAlgebra_separatesPoints :
    ((jointAlgebra d).map (BoundedContinuousFunction.toContinuousMapStarₐ ℝ)).SeparatesPoints := by
  intro z z' hzz'
  obtain ⟨f, hf, hne⟩ : ∃ f : (ℝ × (Fin d → ℝ)) →ᵇ ℝ, f ∈ jointAlgebra d ∧ f z ≠ f z' := by
    by_cases hy : z.1 = z'.1
    · have hu : z.2 ≠ z'.2 := fun hu => hzz' (Prod.ext hy hu)
      set F : (Fin d → ℝ) →ᵇ ℝ := BoundedContinuousFunction.ofNormedAddCommGroup
        (fun v => min (dist v z.2) 1) (by fun_prop) 1 (fun v => by
          rw [Real.norm_eq_abs, abs_of_nonneg (le_min dist_nonneg zero_le_one)]
          exact min_le_right _ _) with hF
      refine ⟨jointGen 0 0 le_rfl le_rfl F, Submodule.subset_span (jointGen_mem _ _ _ _ _), ?_⟩
      rw [jointGen_apply, jointGen_apply]
      simp only [expSplitFun, zero_mul, add_zero, neg_zero, Real.exp_zero, one_mul]
      change min (dist z.2 z.2) 1 ≠ min (dist z'.2 z.2) 1
      rw [dist_self, min_eq_left zero_le_one]
      exact (lt_min (dist_pos.2 hu.symm) one_pos).ne
    · rcases ne_or_eq (max z.1 0) (max z'.1 0) with h | h
      · refine ⟨jointGen 1 0 zero_le_one le_rfl 1, Submodule.subset_span (jointGen_mem _ _ _ _ _),
          ?_⟩
        rw [jointGen_apply, jointGen_apply]
        simp only [BoundedContinuousFunction.coe_one, Pi.one_apply, mul_one, expSplitFun, one_mul,
          zero_mul, add_zero]
        exact fun h' => h (neg_injective (Real.exp_injective h'))
      · have h' : max (-z.1) 0 ≠ max (-z'.1) 0 := by
          intro h'
          apply hy
          rw [← max_zero_sub_max_neg_zero_eq_self z.1, ← max_zero_sub_max_neg_zero_eq_self z'.1,
            h, h']
        refine ⟨jointGen 0 1 le_rfl zero_le_one 1, Submodule.subset_span (jointGen_mem _ _ _ _ _),
          ?_⟩
        rw [jointGen_apply, jointGen_apply]
        simp only [BoundedContinuousFunction.coe_one, Pi.one_apply, mul_one, expSplitFun, one_mul,
          zero_mul, zero_add]
        exact fun h'' => h' (neg_injective (Real.exp_injective h''))
  refine ⟨BoundedContinuousFunction.toContinuousMapStarₐ ℝ f, ?_, hne⟩
  simp only [StarSubalgebra.coe_toSubalgebra, StarSubalgebra.coe_map, Set.mem_image,
    SetLike.mem_coe, exists_exists_and_eq_and]
  exact ⟨f, hf, rfl⟩

/-! ### The finite-`N` and limiting joint laws -/

/-- The joint law of `(NK, u)` under the chart posterior. -/
noncomputable def phaseJointLaw (n : ℕ) (h k : Fin (n + 1) → ℕ) (β N : ℝ)
    (ξ η : (Fin (n + 1) → ℝ) → ℝ) : Measure (ℝ × (Fin (n + 1) → ℝ)) :=
  (phasePosterior n h k β N ξ η).map fun u => (N * ∏ i, u i ^ (2 * k i), u)

theorem measurable_energyPair (n : ℕ) (k : Fin (n + 1) → ℕ) (N : ℝ) :
    Measurable fun u : Fin (n + 1) → ℝ => (N * ∏ i, u i ^ (2 * k i), u) :=
  (measurable_energyMap n k N).prodMk measurable_id

theorem phaseJointLaw_isProbabilityMeasure (n : ℕ) (h k : Fin (n + 1) → ℕ) {β : ℝ} (N : ℝ)
    (hβ : 0 ≤ β) {ξ η : (Fin (n + 1) → ℝ) → ℝ} (hξc : Continuous ξ) (hηc : Continuous η)
    (hηnn : ∀ u ∈ unitBox (n + 1), 0 ≤ η u) (hZ : 0 < origPhaseIntegral n h k β N 1 ξ η) :
    IsProbabilityMeasure (phaseJointLaw n h k β N ξ η) :=
  haveI := phasePosterior_isProbabilityMeasure_of_continuous n h k N hβ hξc hηc hηnn hZ
  Measure.isProbabilityMeasure_map (measurable_energyPair n k N).aemeasurable

/-- The limiting joint law of `(NK, u)`: `Q^ξ` pushed forward by `(y,u) ↦ (y, P_J u)`. -/
noncomputable def spatialJointFaceLaw (h k : Fin (d + 1) → ℕ) (l β : ℝ)
    (ξ η : (Fin (d + 1) → ℝ) → ℝ) : Measure (ℝ × (Fin (d + 1) → ℝ)) :=
  (spatialJointLaw h k l β ξ η).map fun z => (z.1, faceProj h k l z.2)

theorem measurable_facePair (h k : Fin (d + 1) → ℕ) (l : ℝ) :
    Measurable fun z : ℝ × (Fin (d + 1) → ℝ) => (z.1, faceProj h k l z.2) :=
  measurable_fst.prodMk ((measurable_faceProj h k l).comp measurable_snd)

theorem spatialJointFaceLaw_isProbabilityMeasure {n : ℕ} (h k : Fin (n + 1) → ℕ)
    (hk : ∀ i, 0 < k i) {l β : ℝ} (hl : 0 < l) (hβ : 0 < β) (hmin : ∀ i, l ≤ ratioExp h k i)
    {ξ η : (Fin (n + 1) → ℝ) → ℝ} (hξc : Continuous ξ) (hηc : Continuous η)
    (hηnn : ∀ v ∈ closedCube (n + 1), 0 ≤ η v) (hZ : 0 < spatialMass h k l β ξ η) :
    IsProbabilityMeasure (spatialJointFaceLaw h k l β ξ η) :=
  haveI := spatialJointLaw_isProbabilityMeasure h k hk hl hβ hmin hξc hηc hηnn hZ
  Measure.isProbabilityMeasure_map (measurable_facePair h k l).aemeasurable

/-! ### Integrals of the generators -/

theorem phasePosterior_compl_unitBox (n : ℕ) (h k : Fin (n + 1) → ℕ) (β N : ℝ)
    (ξ η : (Fin (n + 1) → ℝ) → ℝ) : phasePosterior n h k β N ξ η (unitBox (n + 1))ᶜ = 0 := by
  unfold phasePosterior
  rw [withDensity_apply _ (measurableSet_unitBox _).compl]
  refine setLIntegral_measure_zero _ _ ?_
  rw [Measure.restrict_apply (measurableSet_unitBox _).compl, compl_inter_self, measure_empty]

/-- On the generators the finite-`N` integral is the weighted energy Laplace transform. -/
theorem phaseJointLaw_integral_gen (n : ℕ) (h k : Fin (n + 1) → ℕ) (β : ℝ) {N : ℝ} (hN : 0 ≤ N)
    {ξ η : (Fin (n + 1) → ℝ) → ℝ} (hξc : Continuous ξ) (hηc : Continuous η)
    (hηnn : ∀ u ∈ unitBox (n + 1), 0 ≤ η u) (hZ : 0 < origPhaseIntegral n h k β N 1 ξ η)
    {s t : ℝ} (F : (Fin (n + 1) → ℝ) →ᵇ ℝ) :
    ∫ z, expSplitFun s t z.1 * F z.2 ∂(phaseJointLaw n h k β N ξ η) =
      spatialLaplace n h k β N ξ η F s := by
  unfold phaseJointLaw
  have hc : Continuous fun z : ℝ × (Fin (n + 1) → ℝ) => expSplitFun s t z.1 * F z.2 :=
    ((continuous_expSplitFun s t).comp continuous_fst).mul (F.continuous.comp continuous_snd)
  rw [integral_map (measurable_energyPair n k N).aemeasurable hc.measurable.aestronglyMeasurable,
    phasePosterior_integral n h k β N hξc.measurable hηc hηnn hZ]
  unfold spatialLaplace origPhaseIntegral phaseIntegrand
  congr 1
  refine setIntegral_congr_fun (measurableSet_unitBox _) fun u hu => ?_
  dsimp only
  have hK : 0 ≤ N * ∏ i, u i ^ (2 * k i) :=
    mul_nonneg hN (Finset.prod_nonneg fun i _ => pow_nonneg (hu i (Set.mem_univ i)).1.le _)
  rw [expSplitFun, max_eq_left hK, max_eq_right (neg_nonpos.2 hK), mul_zero, add_zero,
    show -(s * (N * ∏ i, u i ^ (2 * k i))) = -(s * N * ∏ i, u i ^ (2 * k i)) by ring]
  ring

/-- Fubini for the joint density against `e^{-t y} φ(u)`. -/
theorem integral_spatialJointDensity_exp_mul {n : ℕ} (h k : Fin (n + 1) → ℕ) (hk : ∀ i, 0 < k i)
    {l β : ℝ} (hl : 0 < l) (hβ : 0 < β) (hmin : ∀ i, l ≤ ratioExp h k i)
    {ξ η : (Fin (n + 1) → ℝ) → ℝ} (hξc : Continuous ξ) (hηc : Continuous η) {t : ℝ} (ht : 0 ≤ t)
    {φ : (Fin (n + 1) → ℝ) → ℝ} (hφm : Measurable φ) {C : ℝ}
    (hφ : ∀ u ∈ unitBox (n + 1), |φ u| ≤ C) :
    ∫ z, Real.exp (-(t * z.1)) * φ z.2 * spatialJointDensity h k l β ξ η z ∂(energyBoxMeasure n) =
      (∫ u in unitBox (n + 1), faceWeight h k l η u * φ u * (((β + t) / β) ^ (-l) *
        fluctMoment β (ξ (faceProj h k l u) / Real.sqrt ((β + t) / β)) 0 l 0)) /
        spatialMass h k l β ξ η := by
  have hint : Integrable (fun z : ℝ × (Fin (n + 1) → ℝ) =>
      Real.exp (-(t * z.1)) * φ z.2 * spatialJointDensity h k l β ξ η z) (energyBoxMeasure n) := by
    have h0 := integrable_spatialJointDensity_exp h k hk hl hβ hmin hξc hηc ht
    have := Integrable.bdd_mul (c := C) h0 (hφm.comp measurable_snd).aestronglyMeasurable (by
      try unfold energyBoxMeasure
      rw [Measure.prod_restrict,
        ae_restrict_iff' (measurableSet_Ioi.prod (measurableSet_unitBox _))]
      exact Eventually.of_forall fun z hz => (Real.norm_eq_abs _).trans_le (hφ _ hz.2))
    refine this.congr (Eventually.of_forall fun z => ?_)
    simp only [Function.comp_apply]
    ring
  try unfold energyBoxMeasure
  rw [integral_prod_symm _ hint, ← integral_div]
  refine setIntegral_congr_fun (measurableSet_unitBox _) fun u _ => ?_
  simp only [spatialJointDensity]
  rw [← integral_phaseLawKernel_exp β (ξ (faceProj h k l u)) l hβ ht, mul_div_right_comm,
    ← integral_const_mul]
  refine setIntegral_congr_fun measurableSet_Ioi fun y _ => ?_
  ring

/-- On the generators the limiting integral is the weighted face Laplace functional. -/
theorem spatialJointFaceLaw_integral_gen {n : ℕ} (h k : Fin (n + 1) → ℕ) (hk : ∀ i, 0 < k i)
    {l β : ℝ} (hl : 0 < l) (hβ : 0 < β) (hmin : ∀ i, l ≤ ratioExp h k i)
    {ξ η : (Fin (n + 1) → ℝ) → ℝ} (hξc : Continuous ξ) (hηc : Continuous η)
    (hηnn : ∀ v ∈ closedCube (n + 1), 0 ≤ η v) (hZ : 0 < spatialMass h k l β ξ η) {s t : ℝ}
    (hs : 0 ≤ s) (F : (Fin (n + 1) → ℝ) →ᵇ ℝ) :
    ∫ z, expSplitFun s t z.1 * F z.2 ∂(spatialJointFaceLaw h k l β ξ η) =
      (∫ u in unitBox (n + 1), faceWeight h k l η u * F (faceProj h k l u) *
        (((β + s) / β) ^ (-l) *
          fluctMoment β (ξ (faceProj h k l u) / Real.sqrt ((β + s) / β)) 0 l 0)) /
        spatialMass h k l β ξ η := by
  unfold spatialJointFaceLaw spatialJointLaw
  have hc : Continuous fun z : ℝ × (Fin (n + 1) → ℝ) => expSplitFun s t z.1 * F z.2 :=
    ((continuous_expSplitFun s t).comp continuous_fst).mul (F.continuous.comp continuous_snd)
  rw [integral_map (measurable_facePair h k l).aemeasurable hc.measurable.aestronglyMeasurable,
    integral_withDensity_eq_integral_toReal_smul
      (measurable_spatialJointDensity h k l β hξc hηc).ennreal_ofReal
      (Eventually.of_forall fun _ => ENNReal.ofReal_lt_top),
    ← integral_spatialJointDensity_exp_mul h k hk hl hβ hmin hξc hηc hs
      (φ := fun u => F (faceProj h k l u))
      (F.continuous.measurable.comp (measurable_faceProj h k l)) (C := ‖F‖)
      (fun u _ => (Real.norm_eq_abs _).symm.trans_le (F.norm_coe_le_norm _))]
  refine integral_congr_ae ?_
  rw [Filter.EventuallyEq]
  try unfold energyBoxMeasure
  rw [Measure.prod_restrict, ae_restrict_iff' (measurableSet_Ioi.prod (measurableSet_unitBox _))]
  refine Eventually.of_forall fun z hz => ?_
  obtain ⟨hy, hu⟩ := hz
  have hy0 : 0 < z.1 := hy
  simp only [smul_eq_mul]
  have hd : 0 ≤ spatialJointDensity h k l β ξ η z :=
    div_nonneg (mul_nonneg (faceWeight_nonneg h k l hηnn hu)
      (phaseLawKernel_nonneg β _ l hy0.le)) hZ.le
  rw [ENNReal.toReal_ofReal hd, expSplitFun, max_eq_left hy0.le,
    max_eq_right (neg_nonpos.2 hy0.le), mul_zero, add_zero]
  ring

/-- **Identification of the weighted Laplace limits**: the limit of `spatialLaplace_tendsto`
equals the generator integral of the limiting joint law. -/
theorem spatialLaplace_limit_eq {n : ℕ} (h k : Fin (n + 1) → ℕ) (hk : ∀ i, 0 < k i) {l β : ℝ}
    (hβ : 0 < β) {ξ η : (Fin (n + 1) → ℝ) → ℝ} (hF : 0 < spatialFace h k l β ξ η) {s : ℝ}
    (hs : 0 ≤ s) (F : (Fin (n + 1) → ℝ) → ℝ) :
    spatialFace h k l (β + s) (fun u => ξ u * (β / (β + s))) (fun u => F u * η u) /
        spatialFace h k l β ξ η =
      (∫ u in unitBox (n + 1), faceWeight h k l η u * F (faceProj h k l u) *
        (((β + s) / β) ^ (-l) *
          fluctMoment β (ξ (faceProj h k l u) / Real.sqrt ((β + s) / β)) 0 l 0)) /
        spatialMass h k l β ξ η := by
  rw [spatialFace_temperature h k l hβ hs, spatialFace_eq_faceWeight, spatialFace_eq_faceWeight]
  have hc : (1 / (((multCount (ratioExp h k) l - 1).factorial : ℝ) *
      ∏ i, if ratioExp h k i = l then (k i : ℝ) else 1)) ≠ 0 := by
    refine one_div_ne_zero (mul_ne_zero (by positivity) (Finset.prod_ne_zero_iff.2 fun i _ => ?_))
    split_ifs
    · exact_mod_cast (hk i).ne'
    · exact one_ne_zero
  have h2 : (2 : ℝ) ^ (multCount (ratioExp h k) l - 1) ≠ 0 := pow_ne_zero _ two_ne_zero
  have hI : 0 < ∫ u in unitBox (n + 1),
      faceWeight h k l η u * phaseMoment β (2 * l) (ξ (faceProj h k l u)) := by
    have := spatialMass_pos_of_face h k hk l β ξ η hF
    unfold spatialMass at this
    rw [show (fun u => faceWeight h k l η u * fluctMoment β (ξ (faceProj h k l u)) 0 l 0) =
        fun u => 2 * (faceWeight h k l η u * phaseMoment β (2 * l) (ξ (faceProj h k l u))) from
        funext fun u => by rw [fluctMoment_eq_two_mul_phaseMoment]; ring,
      integral_const_mul] at this
    linarith
  have hA : ∫ u in unitBox (n + 1), faceWeight h k l η u * F (faceProj h k l u) *
      (((β + s) / β) ^ (-l) *
        fluctMoment β (ξ (faceProj h k l u) / Real.sqrt ((β + s) / β)) 0 l 0) =
      ((β + s) / β) ^ (-l) * 2 * ∫ u in unitBox (n + 1),
        faceWeight h k l (fun u => F u * η u) u *
          phaseMoment β (2 * l) (ξ (faceProj h k l u) / Real.sqrt ((β + s) / β)) := by
    rw [← integral_const_mul]
    refine setIntegral_congr_fun (measurableSet_unitBox _) fun u _ => ?_
    unfold faceWeight
    rw [fluctMoment_eq_two_mul_phaseMoment]
    ring
  have hZ' : spatialMass h k l β ξ η = 2 * ∫ u in unitBox (n + 1),
      faceWeight h k l η u * phaseMoment β (2 * l) (ξ (faceProj h k l u)) := by
    unfold spatialMass
    rw [← integral_const_mul]
    refine setIntegral_congr_fun (measurableSet_unitBox _) fun u _ => ?_
    rw [fluctMoment_eq_two_mul_phaseMoment]
    ring
  rw [hA, hZ']
  set I₁ := ∫ u in unitBox (n + 1), faceWeight h k l (fun u => F u * η u) u *
    phaseMoment β (2 * l) (ξ (faceProj h k l u) / Real.sqrt ((β + s) / β)) with hI₁
  set I₀ := ∫ u in unitBox (n + 1),
    faceWeight h k l η u * phaseMoment β (2 * l) (ξ (faceProj h k l u)) with hI₀
  set P := ∏ i, if ratioExp h k i = l then (k i : ℝ) else 1 with hP
  have hP0 : P ≠ 0 := by
    refine Finset.prod_ne_zero_iff.2 fun i _ => ?_
    split_ifs
    · exact_mod_cast (hk i).ne'
    · exact one_ne_zero
  have hf0 : (((multCount (ratioExp h k) l - 1).factorial : ℕ) : ℝ) ≠ 0 := by positivity
  have hI0 : I₀ ≠ 0 := hI.ne'
  field_simp

/-- **Convergence of the generator integrals** along `N_m → ∞`. -/
theorem phaseJointLaw_gen_tendsto (n : ℕ) (h k : Fin (n + 1) → ℕ) (hk : ∀ i, 0 < k i) {β : ℝ}
    (hβ : 0 < β) {η : (Fin (n + 1) → ℝ) → ℝ} (hηc : Continuous η)
    (hηnn : ∀ v ∈ closedCube (n + 1), 0 ≤ η v) {l : ℝ} (hmin : ∀ i, l ≤ ratioExp h k i)
    (hatt : ∃ i, ratioExp h k i = l) {ξ : (Fin (n + 1) → ℝ) → ℝ} (hξc : Continuous ξ)
    (hF : 0 < spatialFace h k l β ξ η) (Nseq : ℕ → ℝ) (hN1 : ∀ m, 1 < Nseq m)
    (hN : Tendsto Nseq atTop atTop) (hZ : ∀ m, 0 < origPhaseIntegral n h k β (Nseq m) 1 ξ η)
    {s t : ℝ} (hs : 0 ≤ s) (F : (Fin (n + 1) → ℝ) →ᵇ ℝ) :
    Tendsto (fun m => ∫ z, expSplitFun s t z.1 * F z.2 ∂(phaseJointLaw n h k β (Nseq m) ξ η))
      atTop (𝓝 (∫ z, expSplitFun s t z.1 * F z.2 ∂(spatialJointFaceLaw h k l β ξ η))) := by
  have hl0 : 0 < l := ratioExp_min_pos h k hk hatt
  have hZξ := spatialMass_pos_of_face h k hk l β ξ η hF
  have hηnn' : ∀ u ∈ unitBox (n + 1), 0 ≤ η u := fun u hu =>
    hηnn u (unitBox_subset_closedCube _ hu)
  simp_rw [fun m => phaseJointLaw_integral_gen n h k β (by linarith [hN1 m] : 0 ≤ Nseq m) hξc hηc
    hηnn' (hZ m) (s := s) (t := t) F]
  rw [spatialJointFaceLaw_integral_gen h k hk hl0 hβ hmin hξc hηc hηnn hZξ hs F,
    ← spatialLaplace_limit_eq h k hk hβ hF hs F]
  exact (spatialLaplace_tendsto n h k hk l β hl0 hβ hmin hatt ξ η F hξc hηc F.continuous hs
    hF.ne').comp hN

/-- Convergence of the integrals of every element of the generated algebra. -/
theorem phaseJointLaw_algebra_tendsto (n : ℕ) (h k : Fin (n + 1) → ℕ) (hk : ∀ i, 0 < k i) {β : ℝ}
    (hβ : 0 < β) {η : (Fin (n + 1) → ℝ) → ℝ} (hηc : Continuous η)
    (hηnn : ∀ v ∈ closedCube (n + 1), 0 ≤ η v) {l : ℝ} (hmin : ∀ i, l ≤ ratioExp h k i)
    (hatt : ∃ i, ratioExp h k i = l) {ξ : (Fin (n + 1) → ℝ) → ℝ} (hξc : Continuous ξ)
    (hF : 0 < spatialFace h k l β ξ η) (Nseq : ℕ → ℝ) (hN1 : ∀ m, 1 < Nseq m)
    (hN : Tendsto Nseq atTop atTop) (hZ : ∀ m, 0 < origPhaseIntegral n h k β (Nseq m) 1 ξ η)
    {g : (ℝ × (Fin (n + 1) → ℝ)) →ᵇ ℝ} (hg : g ∈ jointAlgebra (n + 1)) :
    Tendsto (fun m => ∫ z, g z ∂(phaseJointLaw n h k β (Nseq m) ξ η)) atTop
      (𝓝 (∫ z, g z ∂(spatialJointFaceLaw h k l β ξ η))) := by
  have hl0 : 0 < l := ratioExp_min_pos h k hk hatt
  have hZξ := spatialMass_pos_of_face h k hk l β ξ η hF
  have : ∀ m, IsProbabilityMeasure (phaseJointLaw n h k β (Nseq m) ξ η) := fun m =>
    phaseJointLaw_isProbabilityMeasure n h k (Nseq m) hβ.le hξc hηc
      (fun u hu => hηnn u (unitBox_subset_closedCube _ hu)) (hZ m)
  have : IsProbabilityMeasure (spatialJointFaceLaw h k l β ξ η) :=
    spatialJointFaceLaw_isProbabilityMeasure h k hk hl0 hβ hmin hξc hηc hηnn hZξ
  rw [mem_jointAlgebra] at hg
  induction hg using Submodule.span_induction with
  | mem f hf =>
    obtain ⟨s, t, F, hs, -, hf⟩ := hf
    have hfe : ∀ z, f z = expSplitFun s t z.1 * F z.2 := hf
    simp only [hfe]
    exact phaseJointLaw_gen_tendsto n h k hk hβ hηc hηnn hmin hatt hξc hF Nseq hN1 hN hZ hs F
  | zero =>
    simp only [BoundedContinuousFunction.coe_zero, Pi.zero_apply, integral_zero]
    exact tendsto_const_nhds
  | add f g _ _ hf hg =>
    simp only [BoundedContinuousFunction.coe_add, Pi.add_apply]
    rw [integral_add (BoundedContinuousFunction.integrable _ _)
      (BoundedContinuousFunction.integrable _ _)]
    refine (hf.add hg).congr' (Eventually.of_forall fun m => ?_)
    dsimp only
    rw [integral_add (BoundedContinuousFunction.integrable _ _)
      (BoundedContinuousFunction.integrable _ _)]
  | smul c f _ hf =>
    simp only [BoundedContinuousFunction.coe_smul, smul_eq_mul, integral_const_mul]
    exact hf.const_mul c

/-! ### Tightness -/

/-- The energy Laplace transforms converge (the `F = 1` generators). -/
theorem phaseEnergyLaw_laplace_tendsto (n : ℕ) (h k : Fin (n + 1) → ℕ) (hk : ∀ i, 0 < k i) {β : ℝ}
    (hβ : 0 < β) {η : (Fin (n + 1) → ℝ) → ℝ} (hηc : Continuous η)
    (hηnn : ∀ v ∈ closedCube (n + 1), 0 ≤ η v) {l : ℝ} (hmin : ∀ i, l ≤ ratioExp h k i)
    (hatt : ∃ i, ratioExp h k i = l) {ξ : (Fin (n + 1) → ℝ) → ℝ} (hξc : Continuous ξ)
    (hF : 0 < spatialFace h k l β ξ η) (Nseq : ℕ → ℝ)
    (hN : Tendsto Nseq atTop atTop) (hZ : ∀ m, 0 < origPhaseIntegral n h k β (Nseq m) 1 ξ η)
    {t : ℝ} (ht : 0 ≤ t) :
    Tendsto (fun m => ∫ y, Real.exp (-(t * y)) ∂(phaseEnergyLaw n h k β (Nseq m) ξ η)) atTop
      (𝓝 (∫ y, Real.exp (-(t * y)) ∂(spatialEnergyLimit h k l β ξ η))) := by
  have hl0 : 0 < l := ratioExp_min_pos h k hk hatt
  have hZξ := spatialMass_pos_of_face h k hk l β ξ η hF
  have hηnn' : ∀ u ∈ unitBox (n + 1), 0 ≤ η u := fun u hu =>
    hηnn u (unitBox_subset_closedCube _ hu)
  simp_rw [fun m => phaseEnergyLaw_laplace_spatial n h k β (Nseq m) hξc.measurable hηc hηnn'
    (hZ m) t]
  rw [spatialEnergyLimit_laplace h k hk hl0 hβ hmin hξc hηc hηnn hZξ ht]
  have := (spatialLaplace_tendsto n h k hk l β hl0 hβ hmin hatt ξ η (fun _ => 1) hξc hηc
    continuous_const ht hF.ne').comp hN
  rw [spatialLaplace_limit_eq h k hk hβ hF ht (fun _ => 1)] at this
  simp only [mul_one] at this
  exact this

/-- **Tightness of the joint laws**: energy tightness from the Laplace transforms, and the
location carried by the compact closed cube. -/
theorem phaseJointLaw_tight (n : ℕ) (h k : Fin (n + 1) → ℕ) (hk : ∀ i, 0 < k i) {β : ℝ}
    (hβ : 0 < β) {η : (Fin (n + 1) → ℝ) → ℝ} (hηc : Continuous η)
    (hηnn : ∀ v ∈ closedCube (n + 1), 0 ≤ η v) {l : ℝ} (hmin : ∀ i, l ≤ ratioExp h k i)
    (hatt : ∃ i, ratioExp h k i = l) {ξ : (Fin (n + 1) → ℝ) → ℝ} (hξc : Continuous ξ)
    (hF : 0 < spatialFace h k l β ξ η) (Nseq : ℕ → ℝ) (hN1 : ∀ m, 1 < Nseq m)
    (hN : Tendsto Nseq atTop atTop) (hZ : ∀ m, 0 < origPhaseIntegral n h k β (Nseq m) 1 ξ η) :
    IsTightMeasureSet {phaseJointLaw n h k β (Nseq m) ξ η | m} := by
  have hl0 : 0 < l := ratioExp_min_pos h k hk hatt
  have hZξ := spatialMass_pos_of_face h k hk l β ξ η hF
  have hηnn' : ∀ u ∈ unitBox (n + 1), 0 ≤ η u := fun u hu =>
    hηnn u (unitBox_subset_closedCube _ hu)
  have : ∀ m, IsProbabilityMeasure (phaseEnergyLaw n h k β (Nseq m) ξ η) := fun m =>
    phaseEnergyLaw_isProbabilityMeasure_of_continuous n h k (Nseq m) hβ.le hξc hηc hηnn' (hZ m)
  have : IsProbabilityMeasure (spatialEnergyLimit h k l β ξ η) :=
    spatialEnergyLimit_isProbabilityMeasure h k hk hl0 hβ hmin hξc hηc hηnn hZξ
  have hE := isTightMeasureSet_of_laplace (fun m => phaseEnergyLaw n h k β (Nseq m) ξ η)
    (spatialEnergyLimit h k l β ξ η) (fun m => phaseEnergyLaw_Iio n h k β (by linarith [hN1 m]) ξ η)
    (spatialEnergyLimit_Iio h k l β ξ η) fun t ht =>
      phaseEnergyLaw_laplace_tendsto n h k hk hβ hηc hηnn hmin hatt hξc hF Nseq hN hZ ht
  rw [isTightMeasureSet_iff_exists_isCompact_measure_compl_le] at hE ⊢
  intro ε hε
  obtain ⟨K, hKc, hK⟩ := hE ε hε
  refine ⟨K ×ˢ closedCube (n + 1), hKc.prod (isCompact_closedCube _), ?_⟩
  rintro _ ⟨m, rfl⟩
  have hKm : MeasurableSet K := hKc.isClosed.measurableSet
  have hCm : MeasurableSet (closedCube (n + 1)) := (isCompact_closedCube _).isClosed.measurableSet
  rw [Set.compl_prod_eq_union]
  refine (measure_union_le _ _).trans ?_
  have h1 : phaseJointLaw n h k β (Nseq m) ξ η (Kᶜ ×ˢ univ) =
      phaseEnergyLaw n h k β (Nseq m) ξ η Kᶜ := by
    unfold phaseJointLaw phaseEnergyLaw
    rw [Measure.map_apply (measurable_energyPair n k (Nseq m)) (hKm.compl.prod MeasurableSet.univ),
      Measure.map_apply (measurable_energyMap n k (Nseq m)) hKm.compl]
    congr 1
    ext u
    simp
  have h2 : phaseJointLaw n h k β (Nseq m) ξ η (univ ×ˢ (closedCube (n + 1))ᶜ) = 0 := by
    unfold phaseJointLaw
    rw [Measure.map_apply (measurable_energyPair n k (Nseq m))
      (MeasurableSet.univ.prod hCm.compl)]
    refine measure_mono_null ?_ (phasePosterior_compl_unitBox n h k β (Nseq m) ξ η)
    intro u hu
    simp only [Set.mem_preimage, Set.mem_prod, Set.mem_univ, true_and, Set.mem_compl_iff] at hu
    exact fun hu' => hu (unitBox_subset_closedCube _ hu')
  rw [h1, h2, add_zero]
  exact hK (phaseEnergyLaw n h k β (Nseq m) ξ η) ⟨m, rfl⟩

/-! ### Joint weak convergence -/

set_option maxHeartbeats 1000000 in
-- elaborating the coerced probability-measure sequence against the tightness set is slow
/-- **Joint weak convergence of `(NK, u)` under a continuous spatial phase**: along any
`N_m → ∞`, the joint law converges weakly to `Q̃^ξ = ((y,u) ↦ (y, P_J u))_# Q^ξ`. -/
theorem spatialJointLaw_tendsto (n : ℕ) (h k : Fin (n + 1) → ℕ) (hk : ∀ i, 0 < k i) {β : ℝ}
    (hβ : 0 < β) {η : (Fin (n + 1) → ℝ) → ℝ} (hηc : Continuous η)
    (hηnn : ∀ v ∈ closedCube (n + 1), 0 ≤ η v) {l : ℝ} (hmin : ∀ i, l ≤ ratioExp h k i)
    (hatt : ∃ i, ratioExp h k i = l) {ξ : (Fin (n + 1) → ℝ) → ℝ} (hξc : Continuous ξ)
    (hF : 0 < spatialFace h k l β ξ η) (Nseq : ℕ → ℝ) (hN1 : ∀ m, 1 < Nseq m)
    (hN : Tendsto Nseq atTop atTop) (hZ : ∀ m, 0 < origPhaseIntegral n h k β (Nseq m) 1 ξ η) :
    Tendsto (β := ProbabilityMeasure (ℝ × (Fin (n + 1) → ℝ)))
      (fun m => ⟨phaseJointLaw n h k β (Nseq m) ξ η,
        phaseJointLaw_isProbabilityMeasure n h k (Nseq m) hβ.le hξc hηc
          (fun u hu => hηnn u (unitBox_subset_closedCube _ hu)) (hZ m)⟩) atTop
      (𝓝 ⟨spatialJointFaceLaw h k l β ξ η, spatialJointFaceLaw_isProbabilityMeasure h k hk
        (ratioExp_min_pos h k hk hatt) hβ hmin hξc hηc hηnn
        (spatialMass_pos_of_face h k hk l β ξ η hF)⟩) := by
  refine ProbabilityMeasure.tendsto_of_tight_of_separatesPoints ℝ ?_
    jointAlgebra_separatesPoints fun _ hg => ?_
  · exact phaseJointLaw_tight n h k hk hβ hηc hηnn hmin hatt hξc hF Nseq hN1 hN hZ
  · exact phaseJointLaw_algebra_tendsto n h k hk hβ hηc hηnn hmin hatt hξc hF Nseq hN1 hN hZ hg

/-! ### The conditional energy law -/

/-- **Disintegration of the limiting joint law**: for bounded measurable `f`,
`∫ f dQ̃^ξ = ∫ η(P_Ju) w(u) J_λ(ξ(P_Ju)) (∫ f(y, P_Ju) ρ_{ξ(P_Ju)}(dy)) du / Z_ξ` — the
conditional law of the energy given the location `v` is `ρ_{ξ(v)}`. -/
theorem spatialJointFaceLaw_integral_disintegration {n : ℕ} (h k : Fin (n + 1) → ℕ)
    (hk : ∀ i, 0 < k i) {l β : ℝ} (hl : 0 < l) (hβ : 0 < β) (hmin : ∀ i, l ≤ ratioExp h k i)
    {ξ η : (Fin (n + 1) → ℝ) → ℝ} (hξc : Continuous ξ) (hηc : Continuous η)
    (hηnn : ∀ v ∈ closedCube (n + 1), 0 ≤ η v) (hZ : 0 < spatialMass h k l β ξ η)
    {f : ℝ × (Fin (n + 1) → ℝ) → ℝ} (hfm : Measurable f) {C : ℝ} (hf : ∀ z, |f z| ≤ C) :
    ∫ z, f z ∂(spatialJointFaceLaw h k l β ξ η) =
      (∫ u in unitBox (n + 1), faceWeight h k l η u * fluctMoment β (ξ (faceProj h k l u)) 0 l 0 *
        ∫ y, f (y, faceProj h k l u) ∂(phaseLaw β (ξ (faceProj h k l u)) l)) /
        spatialMass h k l β ξ η := by
  unfold spatialJointFaceLaw spatialJointLaw
  have hfm' : Measurable fun z : ℝ × (Fin (n + 1) → ℝ) => f (z.1, faceProj h k l z.2) :=
    hfm.comp (measurable_facePair h k l)
  rw [integral_map (measurable_facePair h k l).aemeasurable hfm.aestronglyMeasurable,
    integral_withDensity_eq_integral_toReal_smul
      (measurable_spatialJointDensity h k l β hξc hηc).ennreal_ofReal
      (Eventually.of_forall fun _ => ENNReal.ofReal_lt_top)]
  have hint : Integrable (fun z : ℝ × (Fin (n + 1) → ℝ) =>
      f (z.1, faceProj h k l z.2) * spatialJointDensity h k l β ξ η z) (energyBoxMeasure n) := by
    have h0 := integrable_spatialJointDensity_exp h k hk hl hβ hmin hξc hηc (le_refl 0)
    simp only [zero_mul, neg_zero, Real.exp_zero, one_mul] at h0
    exact Integrable.bdd_mul (c := C) h0 hfm'.aestronglyMeasurable
      (Eventually.of_forall fun z => (Real.norm_eq_abs _).trans_le (hf _))
  have heq : ∫ z, (ENNReal.ofReal (spatialJointDensity h k l β ξ η z)).toReal •
      f (z.1, faceProj h k l z.2) ∂(energyBoxMeasure n) =
      ∫ z, f (z.1, faceProj h k l z.2) * spatialJointDensity h k l β ξ η z
        ∂(energyBoxMeasure n) := by
    refine integral_congr_ae ?_
    rw [Filter.EventuallyEq]
    try unfold energyBoxMeasure
    rw [Measure.prod_restrict,
      ae_restrict_iff' (measurableSet_Ioi.prod (measurableSet_unitBox _))]
    refine Eventually.of_forall fun z hz => ?_
    obtain ⟨hy, hu⟩ := hz
    have hy0 : 0 < z.1 := hy
    simp only [smul_eq_mul]
    have hd : 0 ≤ spatialJointDensity h k l β ξ η z :=
      div_nonneg (mul_nonneg (faceWeight_nonneg h k l hηnn hu)
        (phaseLawKernel_nonneg β _ l hy0.le)) hZ.le
    rw [ENNReal.toReal_ofReal hd, mul_comm]
  rw [heq]
  try unfold energyBoxMeasure
  rw [integral_prod_symm _ hint, ← integral_div]
  refine setIntegral_congr_fun (measurableSet_unitBox _) fun u _ => ?_
  simp only [spatialJointDensity]
  have hJ : fluctMoment β (ξ (faceProj h k l u)) 0 l 0 ≠ 0 :=
    (fluctMoment_pos β _ l hβ hl).ne'
  rw [phaseLaw_integral β _ l hβ hl]
  set I := ∫ y in Ioi (0 : ℝ),
    phaseLawKernel β (ξ (faceProj h k l u)) l y * f (y, faceProj h k l u) with hI
  rw [show faceWeight h k l η u * fluctMoment β (ξ (faceProj h k l u)) 0 l 0 *
      (I / fluctMoment β (ξ (faceProj h k l u)) 0 l 0) / spatialMass h k l β ξ η =
      (faceWeight h k l η u / spatialMass h k l β ξ η) * I by field_simp, hI,
    ← integral_const_mul]
  refine setIntegral_congr_fun measurableSet_Ioi fun y _ => ?_
  ring

end Grammar
